version: '3.8'
services:
  # TODO: depends on jaeger, restaurant, notifications
  orders:
    container_name: distributed-morsel-orders
    build:
      dockerfile: Dockerfile
      context: ./orders
      # TODO: separate compose
      target: development
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - JAEGER_HOST=http://jaeger
      # TODO: use this in the code
      - RESTAURANT_HOST=http://restaurant
      - NOTIFICATIONS_HOST=http://notifications
    # TODO: separate compose
    volumes:
      - ./orders:/usr/src/app
      - ./orders/node_modules:/usr/src/app/node_modules
    command: npm run start:debug
  # TODO: depends on jaeger, notifications, eventstore
  restaurant:
    container_name: distributed-morsel-restaurant
    build: ./externalRestaurant
    ports:
      - 8080:8080
  # TODO: depends on jaeger
  notifications:
    container_name: distributed-morsel-notifications
    build: ./notifications
    ports:
      - 8888:8888
    environment:
      - JAEGER_HOST=http://jaeger
  jaeger:
    container_name: distributed-morsel-jaeger
    image: jaegertracing/all-in-one@sha256:81dc725e5470609c63b16e6b0110513c2ce8d459a7d3e1a156cb37b7347a3e93
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  eventstore:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
