version: '3.8'
services:
  # TODO: depends on jaeger, restaurant, notifications
  orders:
    container_name: distributed-morsel-orders
    build: ./orders
    ports:
      - 3000:3000
    environment:
      - JAEGER_HOST=http://jaeger
      # TODO: use this in the code
      - RESTAURANT_HOST=http://restaurant
      - NOTIFICATIONS_HOST=http://notifications
  # TODO: depends on jaeger, notifications
  restaurant:
    container_name: distributed-morsel-restaurant
    build: ./externalRestaurant
    ports:
      - 8080:8080
  # TODO: depends on jaeger
  notifications:
    container_name: distributed-morsel-notifications
    build: ./notifications
    ports:
      - 8888:8888
    environment:
      - JAEGER_HOST=http://jaeger
  jaeger:
    container_name: distributed-morsel-jaeger
    image: jaegertracing/all-in-one@sha256:81dc725e5470609c63b16e6b0110513c2ce8d459a7d3e1a156cb37b7347a3e93
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
